name: Generate GitHub Contribution Snake

on:
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the contribution snake
      - name: Generate Snake
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: "mohammad-sheikh-shahinur-rahman"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: ./output/github-contribution-grid-snake.svg

      # Commit & push the generated SVG
      - name: Commit SVG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./output/github-contribution-grid-snake.svg
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push
